"""empty message

Revision ID: 7fb6464e2679
Revises: 
Create Date: 2023-02-08 19:06:07.095486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fb6464e2679'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('contact_person_name', sa.String(length=100), nullable=False),
    sa.Column('nif', sa.String(length=100), nullable=False),
    sa.Column('contact_person_telf', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('city'),
    sa.UniqueConstraint('contact_person_name'),
    sa.UniqueConstraint('contact_person_telf'),
    sa.UniqueConstraint('country'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('nif')
    )
    op.create_table('region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('resume', sa.Text(), nullable=False),
    sa.Column('photo', sa.String(length=255), nullable=False),
    sa.Column('logo', sa.String(length=255), nullable=False),
    sa.Column('user_region', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_region'], ['user_region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accommodation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('resume', sa.Text(), nullable=False),
    sa.Column('photo', sa.String(length=255), nullable=False),
    sa.Column('logo', sa.String(length=255), nullable=False),
    sa.Column('type_bussiness', sa.Enum('hotel', 'hostal', 'albergue', name='accommodationchoices'), server_default='hotel', nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('resume', sa.Text(), nullable=False),
    sa.Column('photo', sa.String(length=255), nullable=False),
    sa.Column('logo', sa.String(length=255), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patrimony',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('resume', sa.Text(), nullable=False),
    sa.Column('photo', sa.String(length=255), nullable=False),
    sa.Column('logo', sa.String(length=255), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restoration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('resume', sa.Text(), nullable=False),
    sa.Column('photo', sa.String(length=255), nullable=False),
    sa.Column('logo', sa.String(length=255), nullable=False),
    sa.Column('type_bussiness', sa.Enum('bar', 'chiringuito', 'restaurante', name='restorationchoices'), server_default='bar', nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_region_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('restoration_id', sa.Integer(), nullable=True),
    sa.Column('accommodation_id', sa.Integer(), nullable=True),
    sa.Column('patrimony_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodation.id'], ),
    sa.ForeignKeyConstraint(['patrimony_id'], ['patrimony.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.ForeignKeyConstraint(['restoration_id'], ['restoration.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_region_id'], ['user_region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('restoration_id', sa.Integer(), nullable=True),
    sa.Column('accommodation_id', sa.Integer(), nullable=True),
    sa.Column('patrimony_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodation.id'], ),
    sa.ForeignKeyConstraint(['patrimony_id'], ['patrimony.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.ForeignKeyConstraint(['restoration_id'], ['restoration.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    op.drop_table('comments')
    op.drop_table('restoration')
    op.drop_table('patrimony')
    op.drop_table('experience')
    op.drop_table('accommodation')
    op.drop_table('region')
    op.drop_table('user_region')
    op.drop_table('user')
    # ### end Alembic commands ###
